document:
  name: Regolamento comercio su aree pubbliche comune Palermo
  description: |
    Regolamento comercio su aree pubbliche comune Palermo.    
  tags:
    - commercio
    - regolamento 
    - comune Palermo
