document:
  name: Regolamento attività sportive comune di Palermo
  description: |
    Regolamento attività sportive comune di Palermo.    
  tags:
    - sport
    - regolamento 
    - comune Palermo
