document:
  name: Regolamento attivita' sportive del comune di Palermo
  description: |
    Regolamento attivita' sportive del comune di Palermo.    
  tags:
    - sport
    - regolamento 
    - comune Palermo
